<?php

namespace AppBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function findContactAction(){
        $em = $this->getEntityManager();
        $contact = $em->createQuery('SELECT a FROM AppBundle:ContactDetails a WHERE a.id = 1')
            ->getResult()
        ;
        return $contact;
    }
}
